### ISSUE TITLE
Header wide ?

### ISSUE THREAD

**Issue by spacecabbie** [dugalex/DA-Glass#2]
I see it as a file but how do i set the skin to wide ?

**Comment by dugalex** [comment]
header wide is just the same size but without the sidebar with stats

**Comment by spacecabbie** [comment]
Yep sorry about that was staring blind on it for the name i have made it responsive now in css wel have begun to want me to share changes ?

**Comment by dugalex** [comment]
no problem, feel free to share the changes here on github
